# apiVersion: v1
# kind: Service
# metadata:
#   name: devportal-service
# spec:
#   selector:
#     app: devportal   
#   ports:
#     - port: 80    
#       targetPort: 8083
#       nodePort: 30005   
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: devportal-service
spec:
  selector:
    app: devportal
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8083
  type: NodePort