# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: elasticsearch-statefulset
#   labels:
#     app: elasticsearch
# spec:
#   serviceName: "elasticsearch"
#   replicas: 1
#   selector:
#     matchLabels:
#       app: elasticsearch
#   template:
#     metadata:
#       labels:
#         app: elasticsearch
#     spec:
#       containers:
#       - name: elasticsearch
#         image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
#         ports:
#         - containerPort: 9200
 
#         env:
#         - name: discovery.type
#           value: "single-node"
#         - name: xpack.security.enabled
#           value: "false"
#         volumeMounts:
#         - name: es-vol
#           mountPath: /usr/share/elasticsearch/data
        
      
#       volumes:
#         - metadata:
#           name: es-vol
     
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
        env:
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: es-vol
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: es-vol
     

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
 
  selector:
    app: elasticsearch
  ports:
     - protocol: TCP
       port: 9200
       targetPort: 9200
       nodePort: 30009
  type: NodePort