name: Create README for Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  create-readme:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          cd ${{ github.workspace }}
          rm -rf .git  # Remove the existing .git directory if it exists
          git init  # Initialize a new Git repository
          git config --global user.email "kanishkarpadmanaban@gmail.com"
          git config --global user.name "kanish-500"

      - name: Generate README
        run: |
          echo "# Pull Request Title: ${{ github.event.pull_request.title }}" > README.md
          echo -e "\n${{ github.event.pull_request.body }}" >> README.md

      - name: Display generated README
        run: cat README.md

      - name: Commit README
        run: |
          git add README.md
          git commit -m "Create README for pull request"
          git push origin HEAD:${{ github.event.pull_request.base.ref }}
