name: Create README for Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  create-readme:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate README
        run: |
          echo "# Pull Request Title: ${{ github.event.pull_request.title }}" > README.md
          echo -e "\n${{ github.event.pull_request.body }}" >> README.md

      - name: Commit and Push README
        run: |
          cd ${{ github.workspace }}
          git config --local user.email "kanishkarpadmanaban@gmail.com"
          git config --local user.name "kanish-500"
          git add README.md
          git commit -m "Update README for pull request"
          git push


        
